spring.application.name=heat-manager

spring.datasource.url=jdbc:mysql://localhost:3306/game-manager
spring.datasource.username=root
spring.datasource.password=42tfyqa
spring.jpa.hibernate.ddl-auto=update
